[[search_dirs]]
path = "/home/seanp/.config/BetterDiscord Installer"
depth = 10

[[search_dirs]]
path = "/home/seanp/.config/HyprV"
depth = 10

[[search_dirs]]
path = "/home/seanp/.config/JetBrains"
depth = 10

[[search_dirs]]
path = "/home/seanp/.config/Microsoft"
depth = 10

[[search_dirs]]
path = "/home/seanp/.config/Microsoft Office"
depth = 10

[[search_dirs]]
path = "/home/seanp/.config/Microsoft Teams - Preview"
depth = 10

[[search_dirs]]
path = "/home/seanp/.config/QtProject.conf"
depth = 10

[[search_dirs]]
path = "/home/seanp/.config/Raspberry Pi"
depth = 10

[[search_dirs]]
path = "/home/seanp/.config/Thunar"
depth = 10

[[search_dirs]]
path = "/home/seanp/.config/TrenTwins.jpg"
depth = 10

[[search_dirs]]
path = "/home/seanp/.config/Unknown Organization"
depth = 10

[[search_dirs]]
path = "/home/seanp/.config/WebCord"
depth = 10

[[search_dirs]]
path = "/home/seanp/.config/autostart"
depth = 10

[[search_dirs]]
path = "/home/seanp/.config/btop"
depth = 10

[[search_dirs]]
path = "/home/seanp/.config/cef_user_data"
depth = 10

[[search_dirs]]
path = "/home/seanp/.config/dconf"
depth = 10

[[search_dirs]]
path = "/home/seanp/.config/draw.io"
depth = 10

[[search_dirs]]
path = "/home/seanp/.config/flutter"
depth = 10

[[search_dirs]]
path = "/home/seanp/.config/green-recorder"
depth = 10

[[search_dirs]]
path = "/home/seanp/.config/gtk-3.0"
depth = 10

[[search_dirs]]
path = "/home/seanp/.config/hypr"
depth = 10

[[search_dirs]]
path = "/home/seanp/.config/keepassxc"
depth = 10

[[search_dirs]]
path = "/home/seanp/.config/kitty"
depth = 10

[[search_dirs]]
path = "/home/seanp/.config/lazygit"
depth = 10

[[search_dirs]]
path = "/home/seanp/.config/libreoffice"
depth = 10

[[search_dirs]]
path = "/home/seanp/.config/mako"
depth = 10

[[search_dirs]]
path = "/home/seanp/.config/matplotlib"
depth = 10

[[search_dirs]]
path = "/home/seanp/.config/mimeapps.list"
depth = 10

[[search_dirs]]
path = "/home/seanp/.config/nautilus"
depth = 10

[[search_dirs]]
path = "/home/seanp/.config/nvim"
depth = 10

[[search_dirs]]
path = "/home/seanp/.config/nwg-look"
depth = 10

[[search_dirs]]
path = "/home/seanp/.config/obs-studio"
depth = 10

[[search_dirs]]
path = "/home/seanp/.config/pavucontrol.ini"
depth = 10

[[search_dirs]]
path = "/home/seanp/.config/pulse"
depth = 10

[[search_dirs]]
path = "/home/seanp/.config/sddm-rose-pine"
depth = 10

[[search_dirs]]
path = "/home/seanp/.config/spicetify"
depth = 10

[[search_dirs]]
path = "/home/seanp/.config/spotify"
depth = 10

[[search_dirs]]
path = "/home/seanp/.config/starship.toml"
depth = 10

[[search_dirs]]
path = "/home/seanp/.config/swaylock"
depth = 10

[[search_dirs]]
path = "/home/seanp/.config/systemd"
depth = 10

[[search_dirs]]
path = "/home/seanp/.config/teams"
depth = 10

[[search_dirs]]
path = "/home/seanp/.config/thefuck"
depth = 10

[[search_dirs]]
path = "/home/seanp/.config/tms"
depth = 10

[[search_dirs]]
path = "/home/seanp/.config/tmux"
depth = 10

[[search_dirs]]
path = "/home/seanp/.config/visp"
depth = 10

[[search_dirs]]
path = "/home/seanp/.config/vlc"
depth = 10

[[search_dirs]]
path = "/home/seanp/.config/wal"
depth = 10

[[search_dirs]]
path = "/home/seanp/.config/waybar"
depth = 10

[[search_dirs]]
path = "/home/seanp/.config/wlogout"
depth = 10

[[search_dirs]]
path = "/home/seanp/.config/wofi"
depth = 10

[[search_dirs]]
path = "/home/seanp/.config/xfce4"
depth = 10

[[search_dirs]]
path = "/home/seanp/.config/xsettingsd"
depth = 10

[[search_dirs]]
path = "/home/seanp/.config/yay"
depth = 10

[[search_dirs]]
path = "/home/seanp/.config/zoom.conf"
depth = 10

[[search_dirs]]
path = "/home/seanp/.config/zoomus.conf"
depth = 10

[[search_dirs]]
path = "/home/seanp/.config/zsh"
depth = 10

[[search_dirs]]
path = "/home/seanp/school"
depth = 10

[[search_dirs]]
path = "/home/seanp/personal-repos"
depth = 10
