[pyprland]
plugins = ["scratchpads"]

[scratchpads.spotify]
animation = "fromTop"
command = "spotify"
class = "Spotify"
size = "80% 85%"
unfocus = "hide"

[scratchpads.thunar]
animation = "fromTop"
command = "thunar"
class = "thunar"
size = "60% 75%"
unfocus = "hide"
lazy = true

[scratchpads.thunderbird]
animation = "fromTop"
command = "thunderbird"
class = "thunderbird"
size = "90% 90%"
unfocus = "hide"
lazy = true
